const stockProductos = [
 
    {
        id: 1,
        nombre: "Lupino",
        cantidad: 1,
        desc: "Cookie con chispas de chocolate",
        precio: 50,
        img: "IMAGENES/cookieSim2.jpg",
      },
      {
        id: 2,
        nombre: "Amancay",
        cantidad: 1,
        desc: "Cookie deliciosa con semillas integrales",
        precio: 50,
        img: "IMAGENES/cookiesSim3.jpg",
      },
      {
        id: 3,
        nombre: "Canelo",
        cantidad: 1,
        desc: "Cookie de canela, nuez y bañado de chocolate blanco",
        precio: 50,
        img: "IMAGENES/cookienuez.png",
      },
      {
        id: 4,
        nombre: "Lenga",
        cantidad: 1,
        desc: "Cookie especial navideña",
        precio: 50,
        img: "IMAGENES/cookienavideña.png",
      },
      {
        id: 5,
        nombre: "Calandrinia",
        cantidad: 1,
        desc: "Cookie bañada de chocolate blanco y chispas de chocolate",
        precio: 50,
        img: "IMAGENES/cookieblanco.png",
      },
      {
        id: 6,
        nombre: "Chilko",
        cantidad: 1,
        desc: "Cookie  de frutilla con chipas de chocolate",
        precio: 50,
        img: "IMAGENES/cookiefrutillaychoco.png",
      },
      {
        id: 7,
        nombre: "Lavanda",
        cantidad: 1,
        desc: "Super Cookie de chocolate rellena de crema con pedacitos de oreo",
        precio: 50,
        img: "IMAGENES/cookierellena.png",
      },